force-app/main/default/objects/Account/fields/Hobbies__c.field-meta.xml
<CustomField>
    <fullName>Hobbies__c</fullName>
    <label>Hobbies</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Playing Cricket</fullName>
            </value>
            <value>
                <fullName>TV Series</fullName>
            </value>
            <value>
                <fullName>Coding</fullName>
            </value>
            <value>
                <fullName>Computer Games</fullName>
            </value>
            <value>
                <fullName>Science</fullName>
            </value>
            <value>
                <fullName>Reading</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Interested_Country__c.field-meta.xml
<CustomField>
    <fullName>Interested_Country__c</fullName>
    <label>Interested Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Pakistan</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MultipicklistTableControllerTest.cls
@isTest
public class MultipicklistTableControllerTest {
    
    @isTest static void userIsOnAccount() { //This case is for when user is on Account Record Page
        Account acc = new Account(Name='Test Account 1', Hobbies__c='Coding;Science', Interested_Country__c='US;UK;India');
        insert acc;
        
        MultipicklistTableController.getMultipicklistData(acc.Id, null, 'multiSelectFieldSet');
    }
    
    @isTest static void userIsOnOpportunity() { //This case is for when user is on Another Object's Record Page Which have Account Field
        Account acc = new Account(Name='Test Account 2', Hobbies__c='Coding;Science', Interested_Country__c='US;UK;India');
		insert acc;
        
        Opportunity opp = new Opportunity(Name='Test', AccountId = acc.Id, StageName='Closed Won', CloseDate = System.today());
		insert opp;
        
        MultipicklistTableController.getMultipicklistData(opp.Id, 'AccountId', 'multiSelectFieldSet');
    }

}